[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]

size = 18

[keyboard]
bindings = [
	{ key = "C", mods = "Alt", action = "Copy"},
	{ key = "V", mods = "Alt", action = "Paste"},
]