export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"
zstyle ':omz:update' mode auto 

# CASE_SENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

HIST_STAMPS="dd-mm-yyyy"

plugins=(git docker docker-compose brew colorize python ssh ssh-agent sublime tmux z)

source $ZSH/oh-my-zsh.sh

alias subl="open -a 'Sublime Text'"
alias zshconf="subl ~/.zshrc"
alias ohmyzsh="subl ~/.oh-my-zsh"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

